### ISSUE TITLE
compatibility issues with github

### ISSUE THREAD

**Issue by ipatch** [yangyang5214/asciicast2mp4#1]
i gave the docker image a try this afternoon, and it produced a results.mp4 file. i uploaded the file to github but the file will not play in firefox, and i've been getting mixed results with chromium based browsers.

github issues seems to only support 10MB attachments but larger mp4 files can be uploaded to gist and linked using `<video` tags.

https://gist.github.com/ipatch/97c8d10beb66c388082680372a3bb854#gistcomment-4038228

right clicking on the video gives the below raw video URL,

```
https://user-images.githubusercontent.com/613805/150659922-55274a55-9591-4a0d-8431-631a5135912a.mp4
```

**Comment by yangyang5214** [comment]
@ipatch 

Yes, there will be problems with image quality. and consumes a lot of memory resources.

So it is recommended to use js to play text and simulate video effects (by google translate)

![image](https://user-images.githubusercontent.com/23392325/150661988-75f1d652-b291-48a4-8f8d-065db30d4412.png)

--- 

是的，对于大于一分钟的视频，效果不是很好，并且消耗的内存很大( ffmpeg  部分)，所以，推荐使用 [asciinema js](https://asciinema.org/) 来达到模拟播放视频的目的。

**Comment by ipatch** [comment]
it is more of a the final mp4 file generated by the docker container ie. the `results.mp4` does not play with the firefox web browser. i don't think the docker container produces valid mp4 files. or is missing some settings that would allow a web browser such as firefox to play the mp4 file. 🤷‍♂️

i ended up reencoding the mp4 file in shotcut then it was able to play in firefox.

**Comment by yangyang5214** [comment]
@ipatch  Yes, I also think it's a problem with firefox not supporting

maybe , try this https://stackoverflow.com/questions/40760864/how-to-play-mp4-video-in-firefox .(or ignore)
